# anchor for common environment entries
x-common-env: &common-env
    RUN_CONTEXT: docker
    KOI_CONFIG_MODE: docker
    RID_CACHE_DIR: /data/cache

# anchor for cache volume mapping
x-cache-vol: &cache-vol
    - cache_data:/data/cache

# anchor for service defaults
x-service-defaults: &service-defaults
    env_file:
        - ./global.env
    environment:
        <<: *common-env
    volumes:
        - cache_data:/data/cache
    restart: unless-stopped
    networks:
        - koinet

services:
    coordinator:
        <<: *service-defaults
        environment:
            PORT: 8080
        build:
            context: ./koi-net-coordinator-node
            args:
                MODULE_NAME: coordinator_node
                PORT: 8080
        ports:
            - "8080:8080"
        volumes:
            - coordinator_state_data:/app/.koi

    github-sensor:
        <<: *service-defaults
        environment:
            PORT: 8001
        build:
            context: ./koi-net-github-sensor-node
            args:
                MODULE_NAME: github_sensor_node
                PORT: 8001
        ports:
            - "8001:8001"
        depends_on:
            coordinator:
                condition: service_healthy
        volumes:
            - github_state_data:/app/.koi/github_sensor_cache

    hackmd-sensor:
        <<: *service-defaults
        environment:
            PORT: 8002
        build:
            context: ./koi-net-hackmd-sensor-node
            args:
                MODULE_NAME: hackmd_sensor_node
                PORT: 8002
        ports:
            - "8002:8002"
        depends_on:
            coordinator:
                condition: service_healthy
        volumes:
            - hackmd_state_data:/app/.koi/cache

    github-processor:
        <<: *service-defaults
        environment:
            PORT: 8011
        build:
            context: ./koi-net-github-processor-node
            args:
                MODULE_NAME: github_processor_node
                PORT: 8011
        ports:
            - "8011:8011"
        depends_on:
            coordinator:
                condition: service_healthy
            github-sensor:
                condition: service_healthy
        volumes:
            - github_processor_state:/app/.koi/github-processor/cache
            - github_index_db_data:/app/.koi/index_db

    hackmd-processor:
        <<: *service-defaults
        environment:
            PORT: 8012
        build:
            context: ./koi-net-hackmd-processor-node
            args:
                MODULE_NAME: hackmd_processor_node
                PORT: 8012
        ports:
            - "8012:8012"
        depends_on:
            coordinator:
                condition: service_healthy
            hackmd-sensor:
                condition: service_healthy
        volumes:
            - hackmd_processor_state:/app/.koi/hackmd-processor
            - hackmd_index_db_data:/app/.koi/index_db

volumes:
    cache_data:
        driver: local
    coordinator_state_data:
        driver: local
    github_state_data:
        driver: local
    hackmd_state_data:
        driver: local
    github_processor_state:
        driver: local
    hackmd_processor_state:
        driver: local
    github_index_db_data:
        driver: local
    hackmd_index_db_data:
        driver: local

networks:
    koinet:
        driver: bridge
